$ErrorActionPreference = 'Stop'
$version = '8.7'
$gradleDir = ".\.gradle-wrapper\gradle-$version"
$localPropsPath = Join-Path $PSScriptRoot 'local.properties'

function Find-AndroidSdk {
    $candidates = @(
        $env:ANDROID_HOME,
        $env:ANDROID_SDK_ROOT,
        (Join-Path $env:LOCALAPPDATA 'Android\Sdk'),
        (Join-Path $env:USERPROFILE 'Android\Sdk'),
        'C:\Android\Sdk',
        'D:\Android\Sdk'
    ) | Where-Object { $_ -and (Test-Path $_) }

    foreach ($path in $candidates) {
        $normalized = (Resolve-Path $path).Path
        $hasPlatforms = Test-Path (Join-Path $normalized 'platforms')
        $hasPlatformTools = Test-Path (Join-Path $normalized 'platform-tools')
        if ($hasPlatforms -or $hasPlatformTools) {
            return $normalized
        }
    }
    return $null
}

function Write-LocalProperties($sdkPath) {
    $sdkDir = ($sdkPath -replace '\\', '/')
    @(
        '# Auto-generated by build.ps1 — do not commit (already in .gitignore)',
        "sdk.dir=$sdkDir"
    ) | Set-Content -Path $localPropsPath -Encoding UTF8
    Write-Host "Using Android SDK: $sdkPath"
}

$sdkPath = Find-AndroidSdk
if (-not $sdkPath) {
    Write-Host ''
    Write-Host 'Android SDK not found.' -ForegroundColor Red
    Write-Host ''
    Write-Host 'Install Android Studio (recommended), then run this build again:'
    Write-Host '  winget install Google.AndroidStudio'
    Write-Host ''
    Write-Host 'After install, open Android Studio once and complete the setup wizard.'
    Write-Host 'The SDK is usually installed to:'
    Write-Host "  $(Join-Path $env:LOCALAPPDATA 'Android\Sdk')"
    Write-Host ''
    Write-Host 'Or set ANDROID_HOME to your SDK folder, then re-run:'
    Write-Host '  .\build.cmd'
    Write-Host ''
    exit 1
}

Write-LocalProperties $sdkPath

if (!(Test-Path "$gradleDir\bin\gradle.bat")) {
    Write-Host "Downloading Gradle $version..."
    New-Item -ItemType Directory -Path ".\.gradle-wrapper" -Force | Out-Null
    $zip = ".\.gradle-wrapper\gradle-$version-download.zip"
    if (Test-Path $zip) { Remove-Item $zip -Force -ErrorAction SilentlyContinue }
    Invoke-WebRequest -Uri "https://services.gradle.org/distributions/gradle-$version-bin.zip" -OutFile $zip -UseBasicParsing
    Write-Host "Extracting..."
    Expand-Archive -Path $zip -DestinationPath ".\.gradle-wrapper" -Force
    Remove-Item -Path $zip -Force
}

& "$gradleDir\bin\gradle.bat" clean assembleDebug
